<?php

/**
 * @file
 * The module will track user activities on the website.
 */

use Drupal\recently_read\Entity\RecentlyReadType;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;

/**
 * Implements hook_entity_view().
 */
function recently_read_entity_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode): void {
  // Get recently read config for current entity.
  $readTypeConfig = RecentlyReadType::load($entity->getEntityTypeId());

  if ($readTypeConfig && !$entity->in_preview && $view_mode === "full") {
    $current_url = \Drupal::routeMatch();
    // If the current route name is not entity.{entity_type}.canonical, we're not
    // on a detail page.
    if ($current_url->getRouteName() !== 'entity.' . $entity->getEntityTypeId() . '.canonical') {
      return;
    }

    $page_entity = $current_url->getParameter($entity->getEntityTypeId());
    // Check if we can find an entity for the current page.
    if (!$page_entity instanceof EntityInterface) {
      return;
    }

    // Check if the current page_entity is the same as the entity we're currently
    // viewing.
    if ($page_entity->id() !== $entity->id()) {
      return;
    }

    // Check if we should track the current entity_type.
    if ($readTypeConfig->get('enabled') === FALSE) {
      return;
    }

    // Check if we need to track the current bundle.
    if (!empty($readTypeConfig->getTypes()) && !in_array($entity->bundle(), $readTypeConfig->getTypes(), TRUE)) {
      return;
    }

    $build['#attached']['library'][] = 'recently_read/recently_read.insert';
    $build['#attached']['drupalSettings']['recently_read'] = [
      'entity_type' => $entity->getEntityTypeId(),
      'entity_id' => $entity->id(),
    ];
  }
}

/**
 * Implements hook_cron().
 */
function recently_read_cron(): void {
  $config = Drupal::configFactory()->getEditable('recently_read.configuration');
  $recentlyRead = \Drupal::service('recently_read');
  switch ($config->get('delete_config')) {
    case "time":
      $time = $config->get('delete_time');
      $query = \Drupal::entityQuery('recently_read')
        ->accessCheck(TRUE)
        ->condition('created', strtotime($time), '<=');
      $records = $query->execute();
      if ($records) {
        $recentlyRead->deleteRecords($records);
      }
      break;
  }
}
